server:
  port: 8080

spring:
  application:
    name: filter-pattern
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: nada5011
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true